### ISSUE TITLE
Make user aware that he/she has to run notebook before deploying if using declarative widgets

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#100]
Consequence of removing the bower dependency. Specific to declarative widgets.

**Comment by jhpedemonte** [comment]
Any suggestions on what to do here? Best I can think of is to scan page when user selects the deploy menu item, looking for Polymer widgets in the cells if the notebook hasn't been run since last edit.

Of course, not sure if all that is possible within Notebook (can we tell when notebook was last run? etc).

**Comment by parente** [comment]
Could just be a doc thing too. Less magic.

**Comment by Lull3rSkat3r** [comment]
PR #119 adds a note about this in the README.md

**Comment by parente** [comment]
PR is in. Do we want to close with doc being the answer or leave open to find a better answer?

**Comment by dalogsdon** [comment]
I think there should be something in the UI to notify the user. Probably non-intrusive, just a reminder of some sort.

**Comment by parente** [comment]
Before we do anything else, we need to know if this is a problem specific to declarative widgets or not. I really don't want to put in UI that's only there for declarative widgets when we don't have the same problem with ipywidgets or Bokeh or plot.ly or ...

**Comment by parente** [comment]
Update on this: Bokeh doesn't have this problem in @nitind's demo. Bokeh has to be pip installed and thereafter it spews the necessary JS into the DOM when the cells execute. The notebook doesn't have to be run ahead of time.

**Comment by parente** [comment]
I think the doc is as good as we're going to get for now. As we started to refactor this repo to split out the bundling aspects, this issues belongs over in `dashboards_bundlers` instead. I suggest we close it here and later reopen the issue over there if it becomes a problem for users.
