### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#118]
Make the extension work when the notebook server is running under Python 2.7. Will need to run the backend test suite against both on Travis. Can do this either with the python2.7 install in our dev container or outside the container like https://github.com/jupyter-incubator/kernel_gateway does.

Off the top of my head:

* Look at problems with package import changes
* Look at setup.py to see if there's anything 3.x specific about the package
* Add PYTHON param to dev, install, test etc. target in the makefile to allow install against Python 2 or 3 in the container.

See jupyter-incubator/declarativewidgets#50 for the counterpart issue.

**Comment by Lull3rSkat3r** [comment]
PR #122 will close this issue.

**Comment by parente** [comment]
Merged PR. Thanks!

**Comment by parente** [comment]
Kernels don't start because of sh -> bash change. But with sh, python2 env activation doesn't work and we end up running with Python 3.

**Comment by Lull3rSkat3r** [comment]
`source` is a `bash` specific command. The equivalent in plain `sh` is to use `.`. However, when you run `. activate python2` in `sh` you will see some errors and a message saying activate only supports `bash` or `zsh` (this is referenced [here](http://penandpants.com/2014/02/28/using-conda-environments-and-the-fish-shell/) as well).

**Comment by Lull3rSkat3r** [comment]
Found a solution. The shell process which is run in the docker container will always be `bash`. The `source activate python2` will then be run in bash (if running python2, nothing will be run for python3). From here, `sh` is run to start the `ipython` process. The `sh` process will inherit the vars from the previous shell, which has the correct `PATH` for the various versions of python.


In my original change, the `dev-with-widgets` target should work on both python3 and python2 for this reason.

**Comment by Lull3rSkat3r** [comment]
Fix is in PR #128
