### ISSUE TITLE
View menu items and toolbar switcher should use consistent naming

### ISSUE THREAD

**Issue by nitind** [jupyter-incubator/dashboards#123]
The text shown when hovering over the view toolbar buttons doesn't match the actions in the View menu, making it harder to understand that they do the same thing and making them harder to discuss and document.

**Comment by parente** [comment]
@nitind want to take a crack at it? Pretty sure the toolbar items went through review and @jhpedemonte  or @dalogsdon updated the tooltips. Probably just need to change view menu to match.

**Comment by nitind** [comment]
I can do that.
