### ISSUE TITLE
Select and show multiple cells at once in Layout mode

### ISSUE THREAD

**Issue by jtyberg** [jupyter-incubator/dashboards#130]
I have a notebook with 50 cells.  I really just want to have them all show top to bottom in View mode.  I select `Cell > Dashboard > Show All Cells`, but that jumbles them all together.  Blerg.  

So I revert to `Cell > Dashboard > Hide All Cells` and begin to add the cells one-by-one, because when I do this, each cell takes up the full width the way I want it.  There's only one problem, I have to click 50 `+` icons to get all my cells to be shown.  

This got me thinking, even if I'm not adding all 50, boy would it be nice to select multiple and add/show them all at once.

**Comment by parente** [comment]
> This got me thinking, even if I'm not adding all 50, boy would it be nice to select multiple and add/show them all at once.

Wouldn't you still need to somehow indicate the N cells you want (by clicking them?) and then click one "Add All" button for N+1 total clicks?

**Comment by jtyberg** [comment]
I had in mind the standard keyboard/mouse inputs for multi-selection.  Click to select one, scroll to bottom, press Shift key and click the bottom one.  Then click some kind of add button.  That's 4 clicks, counting the Shift key, to show all 50.

I wouldn't even mind clicking 50 times, but it's really hard the way a cell is moved from hidden to shown areas in Layout mode.  Everything gets pushed down when you show a cell, so you have to scroll a bit and find the little '+' on the next cell with the cursor to repeat the process.  After the third time, that's when my head screamed out for multi-selection.

**Comment by parente** [comment]
> even if I'm not adding all 50

I understand select all. I was asking about the "not adding all 50" part. Do you find you're adding contiguous runs of cells often?

The upcoming 4.1 notebook has support for multiple cell selection. We should look at what mechanism it uses and co-opt / mimic it for consistency at the very least.

**Comment by jtyberg** [comment]
Agreed on multi-cell consistency with 4.1.  

Basically, I find myself in this situation where pretty much the whole notebook is fair game for a report style viewing, but I haven't yet switched to the Layout mode to select any cells to show.   I don't think it's something that happens often - just the first time I want to mark all cells in the notebook as "display me" without the input/code.  Ideally, I would just go into Layout mode once, and a few clicks later, I've pretty much got it.  

I've been in Layout mode several times with longer notebooks in situations where I'm more picky about what cells to show.  I have not found myself wanting the multi-select/show in those situations though.

**Comment by parente** [comment]
So maybe revisiting Add All / Remove All is worthwhile. Last time, we decided to keep its "dense packing" behavior for a reason I don't remember. If you could Add All and then just subtract the few you don't want, you'd have what you're asking for I think.

**Comment by parente** [comment]
If #132 lands, I think there's much less of a need for multi-select right now.

**Comment by parente** [comment]
@jtyberg interested in hearing whether this is needed anymore now that `Show all (stacked)` exists.

**Comment by jtyberg** [comment]
I have used the new Show All (Stacked) feature, which is great.  I agree, this feature does not seem necessary now that I can stack my cells all at once.  (I can't think of a time that I've needed it in the past few weeks).

**Comment by parente** [comment]
OK. Will close for now and reopen in the future if the need arises.
