### ISSUE TITLE
Cell > Dashboard > * new option

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#132]
Currently, there are two options:

* Show All Cells - densely packs all cells with output into a dashboard layout
* Hide All Cells - hides all cells

We can satisfy @jtyberg's requirement originally documented in #55 by having 3 options:

* Show All Cells (Packed) - does what it does today
* Show All Cells (Top-to-Bottom) - shows all cells, full width, in notebook order
* Hide All Cells - does what it does today

**Comment by Lull3rSkat3r** [comment]
PR #134 will close this.
