### ISSUE TITLE
Minimum height cells overlap in layout mode

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#144]
To reproduce:

1. Add two cells to the layout, one atop the other.
2. Size the top cell to be as short as the drag allows you to make it.
3. Note the overlap like in this screenshot.

<img width="439" alt="screen shot 2015-11-30 at 9 56 50 am" src="https://cloud.githubusercontent.com/assets/153745/11485838/7979385a-9783-11e5-96bb-49724345e72a.png">

**Comment by dalogsdon** [comment]
This looks like a problem with Gridstack resizing. We set the minimum cell height to be 2 rows, and we also style a minimum height for a dashboard cell to be the same height as 2 rows. Somehow Gridstack is setting a cell height to 1 row, and our minimum height causes it to overflow causing the overlap in the screenshot above.

This is difficult for us to reproduce as it seems to be working properly. However, we have seen this once in the past, but could not reproduce it then either. Are you able to reproduce @parente?

**Comment by dalogsdon** [comment]
We are able to reproduce with a new notebook.

Looks like a problem only the first time viewing the dashboard layout. Somehow the setting for minimum height is not set properly.

**Comment by dalogsdon** [comment]
More precisely, the `data-gs-min-height` attribute was being set on a cell after being added to the dashboard rather than before. This had the effect of causing new and newly re-added cells to have this problem.

**Comment by parente** [comment]
It's back!

![screen shot 2016-01-19 at 5 09 21 pm](https://cloud.githubusercontent.com/assets/153745/12433513/79c2f9ae-becf-11e5-87a6-8785f5faf956.png)

**Comment by dalogsdon** [comment]
Hehe, same flipping of lines needs to occur in another function.
