### ISSUE TITLE
Notebook 4.1b1: Dashboard toolbar does not appear

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#158]
Not sure yet if this is a dashboards incompat or a bug in notebook-4.1.0b1:
```
IPython.toolbar.add_buttons_group(['urth.notebook-view', 'urth.layout-view', 'urth.dashboard-view'],
                'urth-dashboard-view-toolbar-buttons');
```

causes:

![screen shot 2015-12-16 at 5 33 46 pm](https://cloud.githubusercontent.com/assets/153745/11855919/2fcc74e8-a41b-11e5-9de1-b9805be225e2.png)

/cc @Carreau 

EDIT: screenshot of JS console instead of ugly copy/paste

**Comment by Carreau** [comment]
Sorry I missed the Ping.

**Comment by parente** [comment]
Not a problem. Could be our stuff. Quick glance before I have to run til tonight: the function invocation doesn't seem to match anything in the current doc about how to add toolbar buttons, so I'm leaning toward "it's us". I'll dig in later and ping back.

**Comment by Carreau** [comment]
1) I get a problem, where my local install try to load `requirejs-text/text.js.js` with 2 `.js`, which is easy to get around.

2) I investigate the second bug now

**Comment by Carreau** [comment]
Found bug. Will issue PR.

**Comment by parente** [comment]
Was just sitting down now to work on this. Thanks for beating me to it! Glad it wasn't upstream in notebook.
