### ISSUE TITLE
Use new non-global UrthData.setItem API

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#170]
When https://github.com/jupyter-incubator/declarativewidgets/issues/147 lands, we need to update the sentiment demos to use the new, non-global channel APIs in JavaScript.

/cc @lbustelo @deedubbu

**Comment by deedubbu** [comment]
Investigating now as I have a pull request (jupyter-incubator/declarativewidgets#179) being reviewed in the declarative widgets project.

**Comment by parente** [comment]
Thanks @deedubbu . Doing a global search on all the demo notebooks, I only saw the old API used in 2 of them and there in limited fashion. It's probably a simple swap-out.
