### ISSUE TITLE
`urth-timeline` in sentiment boilerplate does not have `start_date` and `end_date` properties

### ISSUE THREAD

**Issue by Lull3rSkat3r** [jupyter-incubator/dashboards#173]
This causes the timeline to not be rendered when the cell is run. The community sentiment notebook does this and can be used as a reference.

**Comment by parente** [comment]
If this is relatively easy to fix, would be good to get it in for 0.4 release real-soon-now so that it lands on the updated jupyter.cloudet.xyz site.

**Comment by Lull3rSkat3r** [comment]
@parente, it looks this was a timing issue. The code that initializes those variables, if they are note set is found [here](https://github.com/jupyter-incubator/dashboards/blob/master/etc/notebooks/sentiment_boilerplate_demo/widgets/urth-timeline/urth-timeline.html#L158). Closing this as invalid.
