### ISSUE TITLE
Hide widget warnings / errors

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#174]
Dashboards should css hide all warning messages when in dashboard mode. Otherwise, we get ugly pink boxes like the one here: jupyter-incubator/declarativewidgets#164.

**Comment by dalogsdon** [comment]
Should be an easy one to knock out, just got to hide `.output_stderr` elements when in dashboard view.

**Comment by dalogsdon** [comment]
PR #176 will hide the pink warning box. Exceptions will still appear like this though:

![image](https://cloud.githubusercontent.com/assets/6362426/12461605/68a8d700-bf7f-11e5-9c41-f50387ad8df8.png)

If you want to get rid of those in the dashboard view, we can hide them too.

**Comment by dalogsdon** [comment]
Also, didn't notice the assignee was set, sorry for stealing the issue ;)

**Comment by parente** [comment]
Go ahead and push that as a PR too. (It ain't stealing if you're fixing things!)

**Comment by parente** [comment]
The version that went in only applies to dashboard view within Jupyter Notebook. Need to move to `dashboad-common.css` so that it works when deployed too.

**Comment by parente** [comment]
Not easy to fit into common because:

- deployed dash doesn't use `grid-stack-item` class
- layout / preview modes do use `grid-stack-item` for cells in the dashboard flow
- layout / preview does not use it for cells that are hidden

Assuming we want to see the stderr/exceptions down in the hidden cells, there's no rule that handles all the cases correctly and does so without introducing specific classes into common.

I think I'll just duplicate the styling over in dashboards_bundlers for the time being.
