### ISSUE TITLE
More options for plus button when adding cell to layout

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#199]
New options. Could be implemented in a drop down from the + icon on each cell.

* Add to top of layout (full width bottom row, default)
* Add to top of dashboard layout (full width top row)
* Add to relative notebook position

Last one is tricky because what if the user has put a cell that appears lower in the notebook flow higher in the dashboard flow than other cells? Maybe the algorithm can be:

1. Degenerate case, if the dashboard layout is empty, just add the cell full width.
2. Get the notebook flow index of the cell being added to the flow. Call this `i`.
3. Search top-left to bottom-right in reading order for the cell with the closest notebook index `j` that does not exceed `i`.
4. Insert the `i`th cell in a new full width row directly below the row containing the `j`th cell. (Why full width? Avoids a tiny cell shove into an existing row with content overflowing and obscuring the controls to make further adjustments.)

**Comment by dalogsdon** [comment]
I did the algorithm as outlined above with the exception of 3. I don't think it is necessary to search in reading order. Just searching in DOM order should be sufficient, so we will insert the cell below the closest previous sibling.

**Comment by dalogsdon** [comment]
Add buttons look like this now:

<img width="141" alt="screen shot 2016-03-24 at 11 53 03 am" src="https://cloud.githubusercontent.com/assets/6362426/14024453/18880b3c-f1b7-11e5-8632-d0d7be45728a.png">
