### ISSUE TITLE
Bokeh demo error when doing `run all`

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards#200]
The default behavior of Bokeh is to load JS resources from a CDN when running `output_notebook()` with no arguments. This causes a comm-related error when `show()` is run before the JS files are loaded.

One solution is to put Boken in inline mode using `output_notebook(bokeh.resources.INLINE)` or setting the environment variable `BOKEH_RESOURCES=inline` when running the notebook server. See https://github.com/bokeh/bokeh/issues/3639#issuecomment-184251673.

**Comment by dalogsdon** [comment]
I tried setting the environment var `BOKEH_RESOURCES=inline` when running `make dev` and that did work.

**Comment by parente** [comment]
Can we just update the notebook to do `output_notebook(bokeh.resources.INLINE)`? Easier if it's right there inline and explicit instead of something that has to be done in the environment.

**Comment by dalogsdon** [comment]
We can update the notebook, and we should document it somewhere, perhaps a plotting section of the README or a wiki page.

**Comment by parente** [comment]
No one will find it on a wiki. And I don't think this is a problem specific to dashboards. The doc for Bokeh must have it. 

For our part, how about we just mention it in the notebook itself?

**Comment by dalogsdon** [comment]
Definitely mention in the notebook.

**Comment by bryevdv** [comment]
FYI: possibly relevant: https://github.com/bokeh/bokeh/pull/4144
