### ISSUE TITLE
Multiple pasted cells get the same layout

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards#202]
This seems like a notebook bug/behavior related to cell metadata.

1. Create a notebook cell. I used Markdown to easily keep track of the cells.
2. Copy and paste the original cell 2 times so there are 3 total notebook cells. Edit each copy to keep track of which cell is which.
3. Enter Dashboard Layout view and edit each cell to be a different width.
4. Switch back to Notebook view and observe each cell's metadata. Notice the metadata for the first pasted cell is the same as the metadata for the second (more generally, last) pasted cell.

It seems that the cell metadata is set for both pasted cells when the 2nd pasted cell's metadata is updated.

Note: If you view each cell's metadata before doing the layout, the problem doesn't occur.

**Comment by parente** [comment]
> Note: If you view each cell's metadata before doing the layout, the problem doesn't occur.

Interesting. Wonder if this is a notebook bug then. @Carreau , any thoughts?

If not, we'll simply have to make sure cell layouts aren't identical when switching to dashboard mode, and warn users to do it before saving and exiting.

**Comment by jhpedemonte** [comment]
I wonder if this isn't an issue in our dashboard extension, where we reference a metadata object and copy/paste just copies the reference rather than the object. Therefore, all of the copied cells reference the same underlying metadata object, causing the issue you describe.

**Comment by parente** [comment]
> copy/paste just copies the reference rather than the object

Well, yes. I guess I'm asking if that's an expected notebook behavior or not, shallow or deep copy. The note @dalogsdon made about viewing the object first seems to suggests the behavior is at least inconsistent.
