### ISSUE TITLE
Add additional view: "report" (stacked)

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards#203]
We currently support creating a **grid-based layout**. But we've noticed that in some situations, this is not what is required for the dashboard. We need some additional views which are either more simplified or provide different functionality:

1. **Report mode**: a simple view which shows cells in notebook order, single column and full width. The only action available to the user is whether to show/hide each cell.

2. **Multi-page mode**: see #206 

---

Selecting between which mode to employ for a notebook could be done using a set of toolbar buttons or the addition of some selection UI to top of notebook (see existing blue help text).

**Comment by parente** [comment]
Multi-page might also address #150 in a different manner than originally proposed.

**Comment by jtyberg** [comment]
Report mode.  :joy:

**Comment by parente** [comment]
Because it :hurtrealbad:.

**Comment by dalogsdon** [comment]
I moved multi-page to #206 per offline discussion with @parente. This issue will deal with the support of multiple dashboard layouts as well as the first of the new layouts: report.

**Comment by parente** [comment]
Maybe you discussed with @jhpedemonte options that would be valid in this mode. It's probably just add to flow and remove from flow by clicking the + / X in the top right of the existing cells?

**Comment by dalogsdon** [comment]
Yes, that exactly.

**Comment by parente** [comment]
Exactly that? YES!

**Comment by parente** [comment]
Since this is going to re-use the gridstack work, I think we can target to 0.5.0. Multipage can stay with 0.6.0 since it's a bigger jump.

**Comment by dalogsdon** [comment]
I used this task to update `dashboard-actions.js` to support multiple layouts and to move metadata manipulation into its own module `dashboard-metadata.js`.

I added an additional view for the report layout:

![image](https://cloud.githubusercontent.com/assets/6362426/14126984/5e60a6c4-f5da-11e5-9f43-080be4a8837b.png)

![image](https://cloud.githubusercontent.com/assets/6362426/14127003/703042ce-f5da-11e5-9d09-9ee9856000b3.png)

**Comment by dalogsdon** [comment]
Discussed with @jhpedemonte about the toolbar button group for layout selection. We decided it would be good to have three buttons as previously: Notebook, Authoring, and Preview. The center Authoring button would have a dropdown to select the layout, and the Preview would automatically show the correct layout based on the Authoring selection. This allows for easy layout addition (multi-page) and reduces potential layout metadata loss when switching layout types.

**Comment by dalogsdon** [comment]
Toolbar looks like this now:

![image](https://cloud.githubusercontent.com/assets/6362426/14253742/4aea2616-fa52-11e5-9a26-4710f338d823.png)

Unfortunately the notebook toolbar addition is for basic button groups, so I had to switch to manually creating the HTML and appending to the toolbar.
