### ISSUE TITLE
Prevent Dashboard from attacking people in their dreams. 

### ISSUE THREAD

**Issue by Carreau** [jupyter-incubator/dashboards#210]
CC @parente sitting just next to me, who knows what I'm talking about and challenged me to open an issue. 

---- 

Observed behavior: Wake up at 5am, all sweating, scared of dashboard.
Expected behavior: Sleep until 7-7:30 well rested. 

--- 

Will understand if bug is closed with "cannot reproduce".

**Comment by parente** [comment]
Need steps to to reproduce.

**Comment by Carreau** [comment]
All might not be relevant but:

- Attend dev meeting for 2 days. 
- Socialise the first with food and drink in the evening, 
- Attend meetup second day with food and drink
  - Meeting should demo a bit of dashboards. 
- Go to bet at 10, 
- Fall asleep, 
- Get nightmares,
- Wake up at 5am.

**Comment by dalogsdon** [comment]
![image](https://cloud.githubusercontent.com/assets/6362426/14155774/c917cb10-f688-11e5-862c-81277fc62663.png)

**Comment by jhpedemonte** [comment]
I really hope @parente or @Carreau show this during a presentation at the dev meeting.

**Comment by Carreau** [comment]
No worries, it's on twitter: https://twitter.com/ProjectJupyter/status/715269379697475584

**Comment by Carreau** [comment]
![qvfv1o4](https://cloud.githubusercontent.com/assets/335567/14156001/15c91c3a-f679-11e5-8ecd-ba1f9dc10eaa.gif)

**Comment by parente** [comment]
Thanks for the steps to reproduce. Will try this evening and report back.

**Comment by Carreau** [comment]
Thanks ! I slepped better. Was probably a race condition.
