### ISSUE TITLE
Demo links broken

### ISSUE THREAD

**Issue by kubark42** [jupyter-incubator/dashboards#216]
Hi--

All the demo links in https://app.mybinder.org:80/2428215814/notebooks/index.ipynb go to 404 pages. Thoughts?

**Comment by parente** [comment]
It seems that the binder image gets rebuilt automatically at times, or by someone who doesn't configure it properly with the Dockerfile option. Unfortunately, there's no access control on who can rebuild in binder yet.

I'll go kick off a rebuild (or you can! :) ). Alternatively, you can use http://jupyter.cloudet.xyz.

**Comment by parente** [comment]
The jupyter-incubator/showcase binder image has been rebuilt. I've also added a note in the README there about using the alternative or contacting us to rebuild it if it happens again.

Thanks for the report!
