### ISSUE TITLE
Remove host dependency on bower

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#22]
We already have the bower requirement within our dev docker container to support urth-widgets. We can piggy back on this to do the minimal bower install for our own dev purposes. Probably just involves a few swizzles in the Makefile. Pay off: you don't need node/bower installed on the host.

**Comment by jhpedemonte** [comment]
Currently, we are doing the following with Node and Bower:

1. Running autoprefixer on our CSS.
2. Installing Gridstack.js and Require.js libraries.

We're unsure how to best update the Makefile to do this before running the actual command in Docker. Do we want to create a script that gets run as the `$(CMD)`, to run the above before starting the Notebook server?

**Comment by parente** [comment]
I was thinking it would just be a separate make target (make js? frontend?) that runs in a container instance that has the host mount. It does its thing. Then there's make dev that just assumes the other one has already run. The former could easily be a dep on the target of the latter like (psuedo code):

```
js:
    docker run -v `pwd`:/src $(IMAGE) npm install

dev: js
    docker run -v ... $(IMAGE)
```

**Comment by jhpedemonte** [comment]
OK, makes sense.

In Makefile, while some targets are using `cloudet/pyspark-notebook-bower` as the image, most are using `jupyter/pyspark-notebook:3.2`, which contains neither node nor bower. Should we switch all to use `cloudet/pyspark-notebook-bower`?

**Comment by dalogsdon** [comment]
Created PR #47 to add a `js` Makefile target.

**Comment by parente** [comment]
Need to switch to the one image other Travis becomes :unamused: with the two image pulls.

**Comment by jhpedemonte** [comment]
So should we change all images in Makefile to use the `*-bower` image? It's just a very small wrapper around the `pyspark` image.
