### ISSUE TITLE
Missing cell decorations in report mode

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#222]
1. Create a brand new notebook
2. Create 3 cells
3. Click the dropdown in the toolbar and report layout button
4. Hover cells and note there's no buttons.

If you go to grid mode first instead, then the buttons appear.

**Comment by parente** [comment]
@dalogsdon Probably a quick fix. Missing some init path for report mode vs grid.

**Comment by dalogsdon** [comment]
When doing the report layout on `test_no_layout` I get an error that it is attempting to access dashboard metadata for a cell. I can add in some more error checking to the metadata code to resolve cases like this.
