### ISSUE TITLE
"make dev" doesn't work out of the box on Ubuntu

### ISSUE THREAD

**Issue by tobinthecloud** [jupyter-incubator/dashboards#228]
I'm very excited about this project. In particular, I'd like to figure out how to integrate it into the Google Cloud Datalab effort.

As a starting point, I'm just trying to build / deploy the repo following the README.md instructions. When I get to "make dev," I get a "Permission Denied" error from the container. After doing a bit of digging around, it appears that it's because I'm not jovyan. If I add a '--user root' flag to the docker run command that "make dev" issues, I can at least get things started. But then I get 404 errors about hidden directories when I attempt to connect to the container on port 9500.

Suggestions? I pretty much followed a straight path through the readme until I got the permission denied error.

**Comment by parente** [comment]
@tobinthecloud Thanks for reporting the problem. I'm surprised that you're not jovyan in the container after running `make build js dev`. You're using the Docker image referenced in the Makefile without changes correct?

**Comment by tobinthecloud** [comment]
Sorry. :/ Something must be wonky with my desktop docker install. I created a VM from scratch, did a clean install and everything works fine.

**Comment by parente** [comment]
Not a problem. If you do end up using this in Google Cloud Datalab, please let us know!
