### ISSUE TITLE
Incorrect popup behavior in scotch decl widgets demo

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#229]
All of the options appear in one unselectable blob. I'm assuming it's an API change.

![screen shot 2016-04-28 at 9 27 57 pm](https://cloud.githubusercontent.com/assets/153745/14906317/2afb47ba-0d88-11e6-8eae-8fc6d3a2ace8.png)

**Comment by aluu317** [comment]
I don't have authorization to assign this to myself, but I'm looking at this now..

**Comment by parente** [comment]
Oh sure. I wasn't in a rush to do it. Just a fyi when you've got a chance and want to look.
