### ISSUE TITLE
unable to export dashboard bundle

### ISSUE THREAD

**Issue by mrfrank8176** [jupyter-incubator/dashboards#232]
Using Jupyter 4.2, I have followed the install instructions for the dashboard bundler and I am able to execute the installation with pip without error. When I run a jupyter notebook, I am able to edit the Dashboard layout and preview. However, there is no option in the notebook to export or save the dashboard as a bundle for stand-alone deployment. How can I enable this feature? Thanks.

**Comment by parente** [comment]
Can you provide the commands you ran to enable both the dashboard layout extension and the bundlers? The full setup requires something like:

```
pip install jupyter_dashboards jupyter_dashboards_bundlers
jupyter dashboards quick-setup --sys-prefix
# this one is noted in the bundlers README
jupyter cms quick-setup --sys-prefix
jupyter dashboards_bundlers quick-setup --sys-prefix
```

**Comment by mrfrank8176** [comment]
That did it! I needed the cms setup. Thanks for the quick help.

**Comment by parente** [comment]
No problem. I'll open an issue in the bundlers repo about updating the README. Cheers!
