### ISSUE TITLE
"Show code on hover" always checked on switch to authoring view, but not always working

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards#239]
1. Switch to authoring view, see "show code on hover" checked
2. Un-check "show code on hover"
3. Switch to notebook view, then back to authoring view
4. "Show code on hover" is checked again, but hover doesn't show the code
5. Un-check and then re-check the button and observe hover code is now visible

Either the code should be shown on hover in step 4 or the button should retain its state (if unchecked) when switching to authoring view.

**Comment by parente** [comment]
In the PR, I went with resetting the checkbox to checked whenever the mode changes for consistency with everything else that gets reset to the defaults.
