### ISSUE TITLE
Remove urth, support v1 metadata spec

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#243]
* [x] Remove all urth references in CSS classes and whatnot
* [x] Adopt v1 metadata spec when https://github.com/jupyter-incubator/dashboards/wiki/Dashboard-Metadata-and-Rendering is finalized
* [x] Decide if/how to support "upgrading" from v0 to v1 metadata in notebooks

DO NOT add any new user-facing features (e.g., NO multi-layout support). This is a cleanup and switcheroo only.

**Comment by parente** [comment]
https://github.com/jupyter-incubator/dashboards/wiki/Dashboard-Metadata-and-Rendering#spec-v1-draft is done. We can / should start seeing what it takes to switch real soon now.

**Comment by parente** [comment]
Re: the metadata, the jury is still out on whether the folks want `metadata.extensions.your_app` or just `metadata.extensions`.

**Comment by dalogsdon** [comment]
Doing the upgrading should be a simple matter of copying over existing data when initializing the metadata structure then deleting the old data.

**Comment by dalogsdon** [comment]
One benefit of this is that we no longer clobber layout data when switching between grid and report layouts.

**Comment by parente** [comment]
I think we can close this one. We'll open others as needed.
