### ISSUE TITLE
Update all demos for 0.6.0 decl widgets compatibility

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#249]
* [x] Manually init the widgets (see https://github.com/jupyter-incubator/declarativewidgets/pull/295)
* [x] Put a markdown note in every demo notebook about what version it's compatible with

**Comment by parente** [comment]
0.6.0.dev0 is out in order to test this work. Requires rebundling of notebooks using decl widgets. The docker-compose dev setup in https://github.com/jupyter-incubator/dashboards_setup will help here.

**Comment by parente** [comment]
Does it make sense to do the try/except around these like in bundlers?

**Comment by jhpedemonte** [comment]
Depends on how much backwards compat we want. Since we're not at 1.0 on delcwidgets, I was only coding for latest.

**Comment by parente** [comment]
Spoke with @lbustelo. https://github.com/jupyter-incubator/declarativewidgets/pull/389 is going to deprecate the urth naming. Examples of the new naming are in that PR.

Let's get this done in a PR on this with the new package name which will go into decl widgets 0.6.0.
