### ISSUE TITLE
Hidden cells added to dashboard during converstion from old spec

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards#256]
1. Open *lorenz.ipynb* from **dashboards_server**.
2. Switch to grid layout.  Notice that there are 3 cells off to the right which should be hidden.

**Comment by jhpedemonte** [comment]
cc @dalogsdon

**Comment by dalogsdon** [comment]
Ah, it looks like empty cells that are auto-hidden didn't have `hidden: true` set.

**Comment by dalogsdon** [comment]
This could have been a bug with how the cell was hidden, but should no longer be an issue now that hidden property is always present. For old notebooks with this issue we should be able to detect a cell in this state if the layout is grid and the cell has an empty `urth.dashboard` object.
