### ISSUE TITLE
Broken example notebooks w/ decl widgets 0.6.x

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards#263]
The following notebooks aren't working correctly (may need to be updated due to underlying Polymer changes?):

* [x] Meetup Outreach demo
    * I think it has trouble creating the Polymer elements which are defined in separate files.
* [x] Sentiment Boilerplate demo
    * `Cannot read property 'getTime' of undefined`
* [x] ~~community_sentiment_demo~~ *(user error)*
    * `Error while invoking function: string indices must be integers`

**Comment by parente** [comment]
Is this before or after the urth init change?

**Comment by parente** [comment]
1. Meetup Outreach Demo
  * Works with ipywidgets==4.1.1, jupyter-declarativewidgets==0.5.1, notebook==4.1.0, jupyter-dashboards==0.5.2
  *  Works with ipywidgets==5.1.5, jupyter-declarativewidgets==0.5.3, notebook==4.2.0, jupyter-dashboards==master
2. Sentiment Boilerplate demo
  * Worked first time with ipywidgets==4.1.1, jupyter-declarativewidgets==0.5.1, notebook==4.1.0, dashboards=0.5.2
  * Worked *every* time with ipywidgets==5.1.5, jupyter-declarativewidgets==0.5.3, notebook==4.2.0, jupyter-dashboards==master

**Comment by jhpedemonte** [comment]
Yes, fail when running with declwidget 0.6.0. Need to talk to the declwidgets guys about some odd issues i'm seeing.

**Comment by jhpedemonte** [comment]
Added **community_sentiment_demo** as well.
