### ISSUE TITLE
Update data for Dashboards?

### ISSUE THREAD

**Issue by napjon** [jupyter-incubator/dashboards#270]
Hi guys, how do we update data for Dashboards? We may have to rerun the entire notebook using something like cron. Is this notebook problem? See [#1034](https://github.com/jupyter/notebook/issues/1034)

**Comment by parente** [comment]
It depends. Can you explain a bit about where you plan to run and view the dashboard? Are you only using the dashboard layout extension within Jupyter Notebook and having each user open the notebook, run it, and interact with the dashboard view in his/her own notebook server? Are you using the Jupyter dashboard server and deploying your notebook there for multiple users to access independently?

**Comment by napjon** [comment]
The second one. Users are public audience that don't even know they're using notebook. They just interact with dashboard.

**Comment by parente** [comment]
If you want the content in the dashboard to refresh on its own, there's a few options:

1. Use ipywidgets, declarative widgets, etc. that can update in response to data changes in the kernel. The streaming meetups demo in this repo is an example.
2. Use widgets like in (1), but trigger their update on a timer. You could set the timer in JS or you could set it in the kernel (e.g., using tornado.ioloop.PeriodicCallback in IPython kernel or equivalent in other kernels).
3. Simply, tell the user to refresh the dashboard page and code your notebook to pull the latest data when it does. 
4. Add JS that does (3) for the user automatically on a timer (`window.location.reload()`)

**Comment by fobyy** [comment]
I just begin to have a look of jupyter and dashboards and get some problems with handling data. Each times i read a csv with pandas in my notebook, when i deploy it on my dashboards, i have an error. (By the way i don't know where to check the logs for the dashboards)

Then, what is the best way to get data in the dashboard?

**Comment by parente** [comment]
When deploying a dashboard to the dash server, the kernel gateway must have access to your data in the same manner as your notebook server. If the data is on local disk on the notebook server, then you have to ensure the kernel gateway also has access to that data on disk (e.g., through a shared volume, through a manual copy). If the data is in a database or pulled through some other network API, then you have to ensure the kernel gateway has network connectivity. And so on.

**Comment by fobyy** [comment]
thx for the answer. I'll check how i can proceed.

**Comment by parente** [comment]
@fobyy I'm going to close this issue as resolved. Feel free to open new ones if you're still having problems.
