### ISSUE TITLE
Uninstall earlier version of dashboards

### ISSUE THREAD

**Issue by gnestor** [jupyter-incubator/dashboards#272]
I have an earlier version of jupyter-incubator/dashboards installed and I haven't been able to fully uninstall it. When I fire up the notebook, I get the following error:

```
[W 13:32:36.516 NotebookApp] Error loading server extension urth.dashboard.nbexts
    Traceback (most recent call last):
      File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/grant/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'urth.dashboard'
```

**Comment by parente** [comment]
What version of notebook are you running?

**Comment by gnestor** [comment]
jupyter 4.1.0
notebook 5.0.0.dev

**Comment by parente** [comment]
With notebook 5.0.0, I think you can use the 4.2 instructions in the README to remove the extension. But probably only if you haven't installed the newer version of the extension on top of it.  If you have, you can downgrade and run the quick-remove steps. Or, you can use `jupyter serverextension list`, find out which config file the old entry is in, and manually remove it.

Neither is ideal. We should really have a note in the README about uninstalling before upgrading if you're coming from one of the pre-package rename versions ...

**Comment by gnestor** [comment]
Thanks @parente. I tried your suggestions but "urth.dashboards" was not being returned by `jupyter serverextension list`. I removed the following offending line and this cleared up the error:

`/Users/grant/.jupyter/jupyter_notebook_config.py:2:c.NotebookApp.server_extensions.append('urth.dashboard.nbexts')`

So, the uninstall script is properly removing dashboards from the `jupyter_notebook_config.json` but not the `jupyter_notebook_config.py` file. I'm not sure if this is a bug with dashboards or notebook? If notebook, I'll close this issue and open one on notebook.

**Comment by parente** [comment]
> So, the uninstall script is properly removing dashboards from the jupyter_notebook_config.json but not the jupyter_notebook_config.py

Ahhh. In version 0.4 of the extension, we switched to using a better mechanism of installing and managing the extension assets in prep for working against the official extension API added in Notebook 4.2 (https://github.com/jupyter-incubator/dashboards/blob/master/CHANGELOG.md#040-2016-01-21). In fact, before 0.4, there was *no* way to uninstall the extension other than the manual steps you just followed.

I don't think there's any action to take today since that change happened 7 months ago. Maybe a note in the README for folks that have a very old version installed?

**Comment by gnestor** [comment]
That makes sense. I just submitted a PR that adds uninstall instructions for users of version 0.4...
