### ISSUE TITLE
What controls the presence of Notebook/Dashboard layout/Dashboar Preview toolbar buttons?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards#276]
I.e. what's the minimum set of steps one needs to take - e.g. `pip install jupyter_dashboards`, `jupyter dashboards quick-setup --sys-prefix` or anything else?

**Comment by nitind** [comment]
That _should_ be enough once you have Jupyter working otherwise.

**Comment by parente** [comment]
I think @nitind answered the question. The README / docs also have the minimal steps. Feel free to reopen if there are more issues.
