### ISSUE TITLE
Is there a way to make dashboards/dashboards_server work with ipywidgets==4.1.1?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards#277]
I know they work with `ipywidgets==5.2.2` and `ipywidgets==5.1.5`. `qgrid` works on `ipywidgets==4.1.1`, hence the question.

**Comment by jhpedemonte** [comment]
I believe it should work. You just need to ensure that the version of ipywidgets that is installed along with the kernel/kernel-gateway is the correct version. If you are testing with [dashboards_setup/docker_deploy](https://github.com/jupyter-incubator/dashboards_setup/tree/master/docker_deploy) recipe, you can do the following to run with v4.1.1:

1. Edit `docker-compose.yml` to set the desired value for `IPYWIDGETS_VER`.
2. `docker-compose build`
3. `docker-compose up`

Let me know if that works for you.

**Comment by rs2** [comment]
Let me test that...

**Comment by parente** [comment]
@rs2 any luck testing the older ipywidgets?

**Comment by rs2** [comment]
Confirmed, `ipywidgets==4.1.1` do `not` work with `dashboards_server`. 
```
index.js:215Uncaught (in promise) Error: Object 'ipython.widget' not found in registry(…)
```

Also `Dockerfile.notebook` does not pin down the `ipywidgets` version, so during the design phase you see the widgets, but once the notebook is published to the server you don't see them anymore. 

Once way to address this is to  pin `ipywidgets` version in the Dockerfile, but I think a better way is to use a remote kernel for both the design phase and thebe, e.g. the nb2kg way: https://github.com/jupyter/kernel_gateway_demos/tree/master/nb2kg.

Shall I send the modified `docker-compose` bundle?

**Comment by parente** [comment]
> Shall I send the modified docker-compose bundle?

To which repository?

**Comment by parente** [comment]
Returning to this after a long hiatus.

> Also Dockerfile.notebook does not pin down the ipywidgets version

The ipywidgets version is pinned in the jupyter/pyspark-notebook base image that the Dockerfile inherits. So I think we're set there.

As for dashboard server not working with ipywidgets 4.1.1, we need to start being more explicit in what we do and do not support in the dashboard server to set expectations. I'll open a PR against the README there soon for discussion.
