### ISSUE TITLE
Local Install Without Docker

### ISSUE THREAD

**Issue by thibaudh** [jupyter-incubator/dashboards#28]
Hi all, 

I have been playing with IBM's dashboard following the README, thus deploying within a docker image. I was wondering if it is at all possible to setup the dashboard system on a normal JupyterHub install. For instance, does the docker image use a special fork of jupiter?

**Comment by thibaudh** [comment]
I am also unsure where you guys have dev discussions... Please let me know if you use something else than github issues.

**Comment by parente** [comment]
The dashboard code is all coded as a Jupyter Notebook extension against the 3.2.x version of the notebook project. With your current dev setup, if you run `make sdist` you should get a source tarball in the `dist/` directory of your clone. You should be able to install that tarball using `pip` anywhere you please with one caveat: the `setup.py` assumes you are installing to `profile_default`. There's no easy way to determine that you want to install against a different user at `pip install` time.

Regarding contact, we're active in `jupyter/jupyter` on gitter, the forums, and here on GitHub the issues. Any of them are fine for dev chats.

**Comment by thibaudh** [comment]
Great, I will try `make sdist` trick. Happy to know that it is pure plugin without changes to Jupyter itself :)

**Comment by parente** [comment]
I added a package section to the README documenting this. Thanks for asking about it!
