### ISSUE TITLE
Meetup outreach business dashboard scenario demo / tutorial

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#30]
Goal: Have a demo based on a real business scenario that incorporates these key points:

* Shows real-time processing
* Surfaces insights
* Allows the user to take action
* Allows the user to see results of actions
* Can apply to meetup.com topics
* Can apply to other data sources / domains entirely (with coding)

Why: Demonstrate how notebooks can be used to prototype dashboards before further investment. Provide it as a tutorial / demo for the community to play with.

## Scenario

I need to drive new sign-ups to my website. One way to do that is to increase attendance at meetups I organize at meetup.com. I want to try to entice people:

1. Who are interested in relevant tech topics
2. While they're thinking about meetups
3. Who are likely to attend a meetup at a given location

To target these users specifically, I'd need to know:

* What related meetups are upcoming? (meetup.com search API)
  * Where are the venues?
  * What's their current RSVP count?
  * UI: Columns or buckets or ... with meetup metadata at the top (name, location, number of RSVPs so far, ...)

* Are there venues for which folks are RSVPing close to any of my  meetups? (meetup.com stream API)
  * Close in location? (don't bother people that aren't coming near my meetup)
  * Close in time? (boost people that will be near my meetup when it is occurring)
  * Close in topic? (don't bother people not interested in topics related to my meetup + boost people that are interested in specific topics ...)
  * UI: maybe a widget to set the distance threshold (but not science-y widgets for setting topic relevancy ...)
  * Analytics: compute relevancy of RSVPer against all of my meetups (distance between other venue and my venue, distance between venue and where the person lives, topic of venue overlap with my venu, topic of interest to user overlap with my venue, ...)

* Who are the people RSVPing nearby to my venues? (meetup.com member profile API + metadata from RSVP stream API)
  * What is the other meetup?
  * How close is the other venue to my venue?
  * How close is the other venue to the user?
  * What are their names?
  * What are their meetup topic interests?
  * UI: put users with above some threshold relevancy into appropriate buckets including info about the user and the other meetup (name, location, other meetup just RSVPed to, interests, link to member page to start a message to user, link to other meetup page to study details / contact meetup organizer)

Once I identify these users, I may want to:

* Inform them soon that they might also be interested in one of my meetups nearby.
  * There is a "Start a discussion link" in the meet-up UI where **humans** can craft notes to other humans. not sure if "i saw you were attending X, you might also check out Y" in a personal note is abuse or not.
* Contact the group offering the other meet-up to run a cross-post campaign (e.g., if I see lots of people also attending that meetup)
  * Same thing: can contact organizer via the meetup page

After I take these actions, I certainly want to:

* See if any of the contacted users do indeed register for my meetup.
  * UI: Once user message link is clicked, user bucket entry shows an icon indicating the user was contacted
* See if there is an uptick in my meetup RSVPs possibly due to my actions.
  * UI: if any user that I contacted appears in the RSVP stream as a "yes" for any of my meetups, that is called out in the UI (turn user gold, put it in a "win" bucket, whatever)

**Comment by jhpedemonte** [comment]
Taking. Working on this with @dalogsdon.

**Comment by jhpedemonte** [comment]
Some ideas for additional work as we are finalizing the first pass:
- Link Bluemix meetups to a map showing location of venue (or group, as fallback).
- broadcast global variables for use in Spark workers (relevant topics, bluemix meetups, etc.)

**Comment by parente** [comment]
Closed by PR #40.
