### ISSUE TITLE
Incorrect conversion of HTML within markdown cell

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#34]
See the `</a>` in the header.

<img width="1290" alt="screen shot 2015-10-13 at 9 41 10 pm" src="https://cloud.githubusercontent.com/assets/153745/10552077/44b7e72e-741f-11e5-956b-2c2646e32702.png">

**Comment by nitind** [comment]
I'll try to make sense of this one.

**Comment by parente** [comment]
If we can't control the converter, let's just update the notebook so that the anchors are outside the heading markdown (assuming that fixes the problem).

**Comment by parente** [comment]
Moving the anchor outside the heading doesn't fix. Still get the anchor leakage.

**Comment by parente** [comment]
Looks like a pandoc limitation. Back off and just use the generated heading IDs.

**Comment by nitind** [comment]
The ipython/tools/tests/Markdown Pandoc Limitations.ipynb notebook mentions "heading anchors", but does not elaborate on it.
