### ISSUE TITLE
Download app bundle fails 500 error when bower fails

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#4]
If any dep can't be downloaded, even temporarily, the whole bundle packaging fails with a 500 error server side. We should do something nicer.

**Comment by parente** [comment]
Ideas so someone can pick this up:

- Catch the subprocess failure up in the bundle handler and rethrow it as a 500, but with a custom error message about what went wrong (i.e., bower fail)
- Catch the subprocess failure down in the call to bower, get the line  from the output that inclues the error, raise as RuntimeError, catch it in the bundle handler, and raise 500 with custom error message indicating the relevant part of the bower error message

**Comment by parente** [comment]
@nitind Can you please have a look at this one too, in conjunction with the others you're working. When you've picked an approach, state it here for quick discussion.

**Comment by nitind** [comment]
No longer applicable. We don't use bower at runtime any more.
