### ISSUE TITLE
Create a boilerplate sentiment dashboard notebook

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#41]
Once we've got one example under our belt in the form of the community sentiment dashboard (issue #14), create a new notebook that tears it down to the barebones widget definitions and layouts. Document the structure of the data required by these widgets and how it must be bound to them. Then fill in very simple "hello world" versions of functions / DataFrames that generate fake data just so the notebook runs top to bottom.

The notebook should be very tutorial-like and walk people through what bits they need to replace and what bits stay. The goal is to demonstrate how UI doesn't have to be rewritten again and again for very similar use cases where only the domain data differs.

**Comment by parente** [comment]
Merged the first PR. @Lull3rSkat3r can you add a link / section to the new index.ipynb now that it exists pointing to your notebook?

**Comment by Lull3rSkat3r** [comment]
@parente PR #114 includes changes for including the boilerplate in the `index.ipynb` file.
