### ISSUE TITLE
Taxi demo no longer autoloads table data

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards#50]
The taxi demo notebook should autoload table data as it hooks up a `paper-menu` with pre-selected item to an `urth-core-function` with an `auto` attribute.

This used to load the table whose data is set by the `auto` function so that the data is initially visible without user interaction to pick a dataset.

Not sure if this is a dashboard or declarative widgets issue.

**Comment by parente** [comment]
Is this related to the widget defect you also opened?

**Comment by dalogsdon** [comment]
Yes

**Comment by dalogsdon** [comment]
This has been resolved by jupyter-incubator/declarativewidgets#63
