### ISSUE TITLE
Put cells at bottom of dashboard with full width when moving hidden -> showing

### ISSUE THREAD

**Issue by jtyberg** [jupyter-incubator/dashboards#56]
In Layout mode, when I 'Add' a cell from the Hidden Cells section, it moves to the top section, but the cell is automatically sized and positioned in this top section (to optimize space).  

If my notebook has quite a few cells, I may add several of them from the Hidden Cells section.  When I scroll up, I am disoriented by the lack of order of the newly added cells.  I may add a couple of plots, along with some markdown or other output cells to go along with them, but they all become jumbled, and I have to mentally piece the cell puzzle back together. 

Admittedly, this is probably only an issue for "dashboards" with quite a few cells.  Still, I'd like the option of turning off the auto-layout.  When I add a hidden cell, it just gets placed full-width below the existing shown cells.  I think this would lend itself to less effort in attaining the final layout.

**Comment by Lull3rSkat3r** [comment]
:+1:

**Comment by parente** [comment]
* Click "+" in hidden to add to showing: stack cells at the bottom of showing in order clicked, full width
* Click eyeball to show all still does dense packing
