### ISSUE TITLE
Meetup outreach re-run with different topic

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#59]
Run it once top to bottom. Then go back and change the topic of interest variable. Then run it again.

![screen shot 2015-10-27 at 9 20 11 am](https://cloud.githubusercontent.com/assets/153745/10759141/066ae294-7c8c-11e5-80b9-de29d62538d6.png)

**Comment by lbustelo** [comment]
Looks like that notebook has a cell that is defining a polymer element. You will always run into that problem unless you protect that cell from multiple executions. 

One idea is to store the return of the Polymer() call to a global and test around it.

**Comment by dalogsdon** [comment]
When we can bundle external files with deployed dashboards (#11) we can define the Polymer element in a separate file. This will also be beneficial for reducing code in the demo notebook.

**Comment by parente** [comment]
For now, do the quick fix: make it global and check if already defined.

**Comment by Lull3rSkat3r** [comment]
Added PR #65 to fix this.

**Comment by parente** [comment]
Will open an enhancement for later about migrating the widget out of the notebook to test @nitind's association work.
