### ISSUE TITLE
Top level index.ipynb guide to all demo / test notebooks

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#60]
We've got a slew of content. Users need a roadmap. This should be something like the index.ipynb we put on jupyter.cloudet.xyz but specific to all the notebooks in this repo. The guide should suggest a sequence of reading through them to learn about dashboards and give a brief description of each to avoid having the user open each one to learn what it is.

**Comment by dalogsdon** [comment]
Working on this
