### ISSUE TITLE
Tooltip or hint area for new users of dashboard layout

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#63]
Need to document a few high-level suggestions somewhere:

* Hover to see icons
* Resize cells
* Eyeball icons
* Hotkey modifier for dragging cells by clicking anywhere (issue #52)
* etc.

Ideas:

Tooltip / popover that shows on first visit to layout mode in a notebook (set a global), but requires a click on an icon near the Dashboard section of the toolbar thereafter.

**Comment by dalogsdon** [comment]
Taking this one.

**Comment by parente** [comment]
I'm going to merge the current PR to get something in to continue working through the others. But some suggestions for improvement:

Should the hint box also talk about the toolbar and how to get back to the notebook? The eyeballs (which will soon be in a menu)?

>  Hide cell: Click  to remove a cell from the dashboard.

Maybe change to "hide a cell in the dashboard view" so people  don't get scared that the cell will get deleted from notebook.

> Show cell: Click  to return a hidden cell to the dashboard.

Add view at the end like the above?

> Dashboard Layout: arrange and size cells. more info

Nitpick: Just looks weird. Maybe make into a sentence? "Arrange and size cells in a dashboard layout. MORE INFO"?

**Comment by parente** [comment]
Additional updates look good. Thanks.
