### ISSUE TITLE
Can't scroll notebook after flipping back from layout

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#64]
1. Open the polymer resize tutorial
2. Run All
3. Scroll to top of notebook
4. Flip to layout
5. Flip right back to notebook
6. Try to scroll

Can't scroll. Scroll bars no longer exist in notebook view.

![bye-bye-scroll](https://cloud.githubusercontent.com/assets/153745/10764287/ce464436-7ca3-11e5-8811-9234dfa3ecd3.gif)

**Comment by parente** [comment]
@Lull3rSkat3r can you have a look? Might be all the other recent fixes also corrected this one.

**Comment by dalogsdon** [comment]
I was still seeing this issue when reviewing changes for issue #62.

**Comment by Lull3rSkat3r** [comment]
When switching to dashboard views an explicit height is being set on the `#notebook` element. It looks like the height is coming from [dashboard.js](https://github.com/jupyter-incubator/dashboards/blob/master/urth_dash_js/notebook/dashboard-view/dashboard.js#L248). When switching back this height is not removed. I am thinking a fix should go into the [ `exitDashboardMode`](https://github.com/jupyter-incubator/dashboards/blob/master/urth_dash_js/notebook/dashboard-view/dashboard-actions.js#L53) function in `dashboard-actions.js`

**Comment by jhpedemonte** [comment]
OK, that's what I figured. Setting the height is necessary when showing the hidden cells area (since we are now absolutely-positioning them). Removing height in `dashboard-actions.js` should be fine.
