### ISSUE TITLE
Deployed sibling polymer element can't find bower installed elements

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards#78]
For the Meetup Outreach demo, we moved some of our code out to HTML files which are siblings of the notebook file. We then import them like so:

```html
%%html
<link rel="import" href="./dynamic-list.html">
<link rel="import" href="./upcoming-meetups.html">
```

The top of each of those HTML files has something like this:

```html
<link rel="import" href="/urth_components/iron-list/iron-list.html"
    is="urth-core-import" package="PolymerElements/iron-list">
<link rel="import" href="/urth_components/paper-toggle-button/paper-toggle-button.html"
    is="urth-core-import" package="PolymerElements/paper-toggle-button#v1.0.10">
<link rel="import" href="/urth_components/paper-material/paper-material.html"
    is="urth-core-import" package="PolymerElements/paper-material">

<dom-module id="upcoming-meetups">
...
```

This works well in the Notebook, but doesn't when we deploy. We get the following error:

```
GET http://192.168.99.100:9500/files/local_dashboards/meetup-outreach/static/urth_components/iron-list/iron-list.html 404 (Not Found)
```

**Comment by lbustelo** [comment]
We still need to take a look at jupyter-incubator/declarativewidgets#22 . It is strange that the relative urth_components path does not work.

**Comment by parente** [comment]
Test again. Various things have changed in dashboards (no more bower install) that might impact behavior.

**Comment by jhpedemonte** [comment]
On current master, we moved the imports of the Polymer elements (iron-resizable-behavior, iron-list, paper-toggle-button and paper-material) to the top of `dynamic-list.html` and `upcoming-meetups.html`.

By itself, that didn't work, since we ran into problem 2 from jupyter-incubator/declarativewidgets#22. So we added a forward slash before `urth_components`, as seen in description above.

This works fine when running in Notebook, but breaks when running a deployed dashboard. But we get different errors than before:

![screen shot 2015-11-03 at 2 09 28 pm](https://cloud.githubusercontent.com/assets/711365/10920188/87e4f0fa-8234-11e5-94ed-4094d444f113.png)

Related to @Lull3rSkat3r's deploy changes?

**Comment by Lull3rSkat3r** [comment]
This looks like Polymer is being loaded twice because of the multiple `dom-module` registrations. I think it is most likely a path issue with how polymer is being loaded.

**Comment by parente** [comment]
Try testing that locally deployed dashboard outside of Jupyter as a webserver. You can try this quickly on your Mac by:

```
cd dashboards/etc/notebooks/local_dashboards/whatever_the_path_is
python -m SimpleHTTPServer
```

and then hit http://localhost:8000/. The dashboard should load. I'd like to see if you get the same errors or different ones.

**Comment by jhpedemonte** [comment]
Updated to latest widgets and moved imports into `dynamic-list.html` and `upcoming-meetups.html`. But as advised by @deedubbu, I **did not** add a leading slash.

I no longer see the long list of errors, but the Upcoming Meetups list doesn't load correctly (when running in the notebook or deployed). It seems that it (eventually) gets the `iron-list`, but it does not load correctly with data. Talking to @deedubbu, this seems to be a timing issue (jupyter-incubator/declarativewidgets#25).

I tested the deployed dashboard using a non-Jupyter webserver and it works exactly as it does from Jupyter itself (and notebook) -- meaning, Upcoming Meetups list doesn't load, but candidates list does show when streaming.

**Comment by parente** [comment]
For the record, the demo is working around this problem but elevating the dependency links to the notebook from of in the widget HTML files.

**Comment by parente** [comment]
Back burnering until widget defect is resolved.

**Comment by parente** [comment]
This probably warrants retesting both with:

1. Local deploy
2. Dashboard server

A short writeup on what works and what doesn't still is the first step. Might be a decl widgets issue still or might be a bundlers / dash server issue.

**Comment by nitind** [comment]
Executing in the notebook, polymer.html itself raises status 404 errors for /urth_components/iron-list/iron-list.html, urth_components/paper-toggle-button/paper-toggle-button.html, and /urth_components/paper-material/paper-material.html.

Locally deployed, meetup-outreach is initially disabled by https://github.com/jupyter-incubator/dashboards_bundlers/blob/master/dashboards_bundlers/local_deploy/__init__.py#L175 . With 0.5.2., `declarativewidgets` is present instead of `urth_widgets` (https://github.com/jupyter-incubator/declarativewidgets/commit/4e5ff1b109bb33b69ecc11beda0aa2af7e65f11c), but there are still problems getting the dashboard to display after updating that.

**Comment by nitind** [comment]
When deployed locally, it's still 404s for /files/local_dashboards/meetup-outreach/static/urth_components/iron-list/iron-list.html as well as urth_components `paper-toggle-button/paper-toggle-button.html` and `paper-material/paper-material.html`.

**Comment by parente** [comment]
> Locally deployed, meetup-outreach is initially disabled by https://github.com/jupyter-incubator/dashboards_bundlers/blob/master/dashboards_bundlers/local_deploy/__init__.py#L175 . 

Hm. Shouldn't be. Either the old version with the old path should work or the new one. Else we've got a backward compat bug that we shouldn't have.

> With 0.5.2., declarativewidgets is present instead of urth_widgets (jupyter-incubator/declarativewidgets@4e5ff1b), but there are still problems getting the dashboard to display after updating that.

I believe the README for decl widgets 0.5.2 says it will only work with ipywidgets 5.1.x and up. Our dev containers are still using ipywidgets 4.x and I think the README in bundlers says thebe only works with 4.x anyway.

**Comment by nitind** [comment]
Once properly deployed, aside from a logged "Uncaught TypeError: Cannot read property 'register' of null", the dashboard works properly both deployed locally and on the dashboard server.

**Comment by nitind** [comment]
Closing after manual test.
