### ISSUE TITLE
Show cell's row/col index in Notebook's dashboard view

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#8]
Sections of a dashboard can be fetched with row and cell URL args on deployed dashboards. But findings the row/col values requires inspecting the DOM at runtime. Expose these in the dashboard layout UI.

**Comment by dalogsdon** [comment]
Is there still any interest in enhancing the row/col query feature?

**Comment by parente** [comment]
Every embedding use I've seen in a demo has embedded the entire dashboard, not row/col. I say pass on this for now unless you really want to tackle it.

**Comment by jhpedemonte** [comment]
Nah, let's close this. If it becomes necessary in the future, we can open another issue.
