### ISSUE TITLE
Don't copy bower_components if dashboard isn't using declarative widgets

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#84]
We currently protect against the case when declarative widgets aren't installed. But we do still continue to copy `bower_components` into every dashboard package, even when the notebook being converted doesn't use the widgets.

jupyter-incubator/declarativewidgets#75 will help, but I think this is possible even now if we have a sane way of determining if the notebook is using declarative widgets or not.

**Comment by Lull3rSkat3r** [comment]
We should be able to sanely achieve this by looking for anything that is an `urth-core-import` and if we find it we can copy.

**Comment by Lull3rSkat3r** [comment]
PR #106 will resolve this issue.
