### ISSUE TITLE
Create a demo that uses other widget libraries in a dashboard

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#86]
We need to show that dashboards don't only work with declarative widgets. Create a really simple demo that uses Bokeh or bqplot or ... whatever in a simple dashboard layout. Bonus: see if it can be deployed locally or if new, special hooks are required for the particular library.

**Comment by parente** [comment]
Few edits to make in the PR.

@nitind, when you tested this as a deployed dashboard, did you hit it via the Jupyter `/files` endpoint? Can you try accessing the dashboard UI via an external web server like `python -m SimpleHTTPServer`? I'm wondering if everything Bokeh needs is shoved into the DOM when a cell runs or if it happens to be picking things up by virtue of the dashboard running within Jupyter.

**Comment by nitind** [comment]
I had been testing it through /files, but running the built dashboard via "python -m SimpleHTTPServer" in an environment lacking bokeh and using the still-running IPython instance as its kernel server worked as intended; the plot was regenerated and reset directly as base64 image data.

**Comment by parente** [comment]
Perfect. Good to know. 

@lbustelo Above suggests bokeh is an example of kernel lib spewing out whatever is needed in the frontend in a way that (apparently) doesn't have a race condition.  FWIW.
