### ISSUE TITLE
Outreach demo should filter tracked meetups

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#96]
1. Left-side upcoming meetups panel is tracking meetup A
2. User 1 appears in the right-side meetup candidates because he/she RSVPs for meetup A (hmm ...)

To be more realistic, I think we'd want to filter user 1 from the candidate list. We don't want to bother a user who just registered for ~~a meetup~~ one of our meetups to register again for another meetup right away.

**Comment by dalogsdon** [comment]
> We don't want to bother a user who just registered for a meetup to register again for another meetup right away.

The right side users have all just RSVP'd for a Meetup.

Regardless if the Meetup was from the left side or not, if there is another one close by should we send a message about it? Or do we assume if they are already attending Meetups in the area around our topic that they are most likely aware of other similar Meetups in the area?

**Comment by parente** [comment]
Clarification:

> We don't want to bother a user who just registered for **one of our** meetups to register again for another meetup right away.

**Comment by dalogsdon** [comment]
It looks like we are currently filtering implicitly on the topic like this:

```python
def topic_filter(rsvp):
    return (rsvp['response'] == 'yes' and
            any(topic['urlkey'] in RELEVANT_TOPICS and topic['urlkey'] != PROD_TOPIC
                for topic in rsvp['group']['group_topics']))
```

The check for `topic['urlkey'] != PROD_TOPIC` can be replaced with a more explicit loop through our meetups.
